# Generated by Django 3.1.1 on 2020-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='img',
            field=models.ImageField(null=True, upload_to='static/static_dirs/download/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(null=True, upload_to='static/static_dirs/download/'),
        ),
    ]
